package pt.ulusofona.lp2.deisiJungle;

public enum InitializationErrorCode {
    
    INVALID_ID_WITHOUT_NUMBERS,
    INVALID_ID_WITH_NEGATIVE_NUMBERS,
    INVALID_PLAYERS_WITH_SAME_ID,
    INVALID_PLAYER_NAME,
    INVALID_JUST_ONE_TARZAN,
    INVALID_NUMBER_OF_PLAYERS,
    INVALID_SPECIE_INEXISTANTE,
    INVALID_FOOD_POSITION,
    INVALID_FOOD_DOES_NOT_EXIST,
    INVALID_FOOD_POSITION_NOT_NUMBER
}
